export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/d1aFl8AQ3dFMsGbeF5wk6BOUwq8.jpg",
    genre_ids: [],
    id: 209374,
    origin_country: ["US"],
    original_language: "es",
    original_name: "Top Chef VIP",
    overview:
      "Guinness world chef championship program held in california.The birth of world tastiest food kitchen.",
    popularity: 2969.289,
    poster_path: "/cw6M4c2MpLSzqzmrrqpSJlEbwCF.jpg",
    first_air_date: "2022-08-09",
    name: "Top Chef around the world comes to know who is the the real champion of this conset",
    vote_average: 9,
    vote_count: 5,
  },
];

export const FAKE_RECOMMENDATION = [
  {
    backdrop_path: "/va6iR1UBVvbj9xFKbK1XHvALb98.jpg",
    id: 233952,
    original_name: "老家伙",
    overview:
      "Xiao Chang Qing, Sun Qian Cheng and Chen Xin Cheng worked hard all their lives. After retirement, they finally got together and co-founded a warm retirement community. In the community, they solved problems that elderly people faced, and in the process, they recognized their own problems and reconciled with their family and with themselves",
    poster_path: "/4edgc2TuV3PP7FvFV2zzWDRagNP.jpg",
    media_type: "tv",
    adult: false,
    name: "Golden Trio",
    original_language: "zh",
    genre_ids: [18],
    popularity: 23.276,
    first_air_date: "2024-05-14",
    vote_average: 6.056,
    vote_count: 9,
    origin_country: ["CN"],
  },
  {
    backdrop_path: "/yviKDevRL5hmKA4MhKFGFyr0cW9.jpg",
    id: 216562,
    original_name: "Special Forces: World's Toughest Test",
    overview:
      "Celebrities endure some of the harshest, most grueling challenges from the playbook of the actual special forces selection process; their goal is not to win votes and face eliminations — for them it is just about survival.",
    poster_path: "/utHIefqz4rxTh6JntqSOST8rroS.jpg",
    media_type: "tv",
    adult: false,
    name: "Special Forces: World's Toughest Test",
    original_language: "en",
    genre_ids: [10764],
    popularity: 9.538,
    first_air_date: "2023-01-04",
    vote_average: 8,
    vote_count: 10,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/s92ZvqE4gWOrZq60AKvhgZZxDY4.jpg",
    id: 240909,
    original_name: "La Casa de los Famosos Colombia",
    overview: "",
    poster_path: "/lCn94cscNlFToXIbIWRSGBqb20Q.jpg",
    media_type: "tv",
    adult: false,
    name: "La Casa de los Famosos Colombia",
    original_language: "es",
    genre_ids: [10764],
    popularity: 66.842,
    first_air_date: "2024-02-11",
    vote_average: 6.28,
    vote_count: 25,
    origin_country: ["CO"],
  },
  {
    backdrop_path: "/vcFW09U4834DyFOeRZpsx9x1D3S.jpg",
    id: 57243,
    original_name: "Doctor Who",
    overview:
      "The Doctor is a Time Lord: a 900 year old alien with 2 hearts, part of a gifted civilization who mastered time travel. The Doctor saves planets for a living—more of a hobby actually, and the Doctor's very, very good at it.",
    poster_path: "/4edFyasCrkH4MKs6H4mHqlrxA6b.jpg",
    media_type: "tv",
    adult: false,
    name: "Doctor Who",
    original_language: "en",
    genre_ids: [10759, 18, 10765],
    popularity: 560.386,
    first_air_date: "2005-03-26",
    vote_average: 7.516,
    vote_count: 2919,
    origin_country: ["GB"],
  },
  {
    backdrop_path: "/xy92C7oWrvd31rHcwM0MhqI5s1x.jpg",
    id: 73481,
    original_name: "Ecomoda",
    overview:
      "Ecomoda is a sequel series to RCN Televisión's I am Betty, the ugly in 2001. It tells the story of Armando and Betty's married life, as well as new small stories with their parents and new characters. Its main plot is the future relationship between Ecomoda, the Fashion Group, and Hugo Lombardi.\n\nIt stars Jorge Enrique Abello and Ana María Orozco, along with Julián Arango, Ricardo Vélez, Lorena Meritano, and Geoffrey Deakin.\n\nDespite having great ratings, it did not experience the same success as its predecessor, in addition to the absence of the main roles of Natalia Ramirez and Lorna Paz from the original series, ending 5 months after its premiere.",
    poster_path: "/eQgvi0yufzRV8A3i4lVheMxU2RN.jpg",
    media_type: "tv",
    adult: false,
    name: "Ecomoda",
    original_language: "es",
    genre_ids: [35, 18],
    popularity: 25.149,
    first_air_date: "2001-08-24",
    vote_average: 7.852,
    vote_count: 1052,
    origin_country: ["CO"],
  },
  {
    backdrop_path: "/vbz8B3pIrGjWKY6Y3OhUDVugHz8.jpg",
    id: 693,
    original_name: "Desperate Housewives",
    overview:
      "Looking down on her friends and family isn't a way of life for Mary Alice Young... it's a way of death. One day, in her perfect house, in the loveliest of suburbs, Mary Alice ended it all. Now she's taking us into the lives of her family, friends and neighbors, commenting from her elevated P.O.V.",
    poster_path: "/fToBWkwVNjYzH6mjrEq5JDYRoLx.jpg",
    media_type: "tv",
    adult: false,
    name: "Desperate Housewives",
    original_language: "en",
    genre_ids: [9648, 18, 35],
    popularity: 290.524,
    first_air_date: "2004-10-03",
    vote_average: 7.937,
    vote_count: 1787,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/27qMrYslAN7LGMpXWKHNm0EkVRy.jpg",
    id: 91875,
    original_name: "Prodigal Son",
    overview:
      "The son of a notorious serial killer becomes an acclaimed criminal psychologist who uses his unique insight into how killers think to help the NYPD.",
    poster_path: "/1huPpms7f5MwBq37en8lOUnF1Zg.jpg",
    media_type: "tv",
    adult: false,
    name: "Prodigal Son",
    original_language: "en",
    genre_ids: [80, 18, 9648],
    popularity: 50.746,
    first_air_date: "2019-09-23",
    vote_average: 8.18,
    vote_count: 403,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/8KtphbDARuisrYYr7DVELnJLRWA.jpg",
    id: 126485,
    original_name: "무빙",
    overview:
      "Children who live in hiding with superpowers, along with their parents who live with painful secrets of the past, face enormous dangers together.",
    poster_path: "/vf9SNXNAFqzKBGksFwrXhkg9cb7.jpg",
    media_type: "tv",
    adult: false,
    name: "Moving",
    original_language: "ko",
    genre_ids: [9648, 18],
    popularity: 106.294,
    first_air_date: "2023-08-09",
    vote_average: 8.4,
    vote_count: 150,
    origin_country: ["KR"],
  },
  {
    backdrop_path: "/k7T9xRyzP41wBVNyNeLmh8Ch7gD.jpg",
    id: 18165,
    original_name: "The Vampire Diaries",
    overview:
      "The story of two vampire brothers obsessed with the same girl, who bears a striking resemblance to the beautiful but ruthless vampire they knew and loved in 1864.",
    poster_path: "/gbp4zM0FE0n23X4UFY5EBlacrog.jpg",
    media_type: "tv",
    adult: false,
    name: "The Vampire Diaries",
    original_language: "en",
    genre_ids: [18, 10765],
    popularity: 605.396,
    first_air_date: "2009-09-10",
    vote_average: 8.336,
    vote_count: 8770,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/jbTqU6BJMufoMnPSlO4ThrcXs3Y.jpg",
    id: 1434,
    original_name: "Family Guy",
    overview:
      "Sick, twisted, politically incorrect and Freakin' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he's not very bright but has a passion for movies). The final member of the family is Brian - a talking dog and much more than a pet, he keeps Stewie in check whilst sipping Martinis and sorting through his own life issues.",
    poster_path: "/y0HUz4eUNUe3TeEd8fQWYazPaC7.jpg",
    media_type: "tv",
    adult: false,
    name: "Family Guy",
    original_language: "en",
    genre_ids: [16, 35],
    popularity: 964.02,
    first_air_date: "1999-01-31",
    vote_average: 7.337,
    vote_count: 4214,
    origin_country: ["US"],
  },
];
